name: plant_detector
description: Detect plant condition from images.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.1.1
  image_picker: ^0.6.7+17
  lottie: ^1.0.1
  url_launcher: ^6.0.2
  timeline_tile: ^2.0.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/

  fonts:
    - family: cascadia
      fonts:
        - asset: assets/fonts/CascadiaCode.ttf
